Repository fps-game-jam-org/game-off-2020, pull requests merged in 2020-11, with the labels that each got.

#25 added GPLv3
  LICENSE
Labels: documentation

#28 Feature/spacial gravity v2
  Assets/Art/Sprites/AnimatedSprites/README.md
  Assets/Art/Sprites/AnimatedSprites/atmosphere.png
  Assets/Art/Sprites/AnimatedSprites/atmosphere.png.meta
  Assets/Art/Sprites/AnimatedSprites/meteorBrown_small2.png
  Assets/Art/Sprites/AnimatedSprites/meteorBrown_small2.png.meta
  Assets/Art/Sprites/AnimatedSprites/ufoBlue.png
  Assets/Art/Sprites/AnimatedSprites/ufoBlue.png.meta
  Assets/Prefabs/Enemies/Missile.prefab
  Assets/Prefabs/Enemies/Missile.prefab.meta
  Assets/Prefabs/Environment/Planet.prefab
  Assets/Prefabs/Environment/Planet.prefab.meta
  Assets/Scenes/Tests/testSpacialGravity.unity
  Assets/Scenes/Tests/testSpacialGravity.unity.meta
  Assets/Scripts/Core/CircleGravity2D.cs
  Assets/Scripts/Core/CircleGravity2D.cs.meta
  Assets/Scripts/Core/README.md
  Assets/Scripts/Core/SpacialGravityReceiver.cs
  Assets/Scripts/Core/SpacialGravityReceiver.cs.meta
  Assets/Scripts/Demos.meta
  Assets/Scripts/Demos/README.md
  Assets/Scripts/Demos/README.md.meta
  Assets/Scripts/Demos/ShootMissileOnClick.cs
  Assets/Scripts/Demos/ShootMissileOnClick.cs.meta
  Assets/Scripts/Tests/PlayMode/TestCircleGravity2D.cs
  Assets/Scripts/Tests/PlayMode/TestCircleGravity2D.cs.meta
  Assets/Scripts/Tests/PlayMode/TestSpacialGravityReceiver.cs
  Assets/Scripts/Tests/PlayMode/TestSpacialGravityReceiver.cs.meta
  ProjectSettings/TagManager.asset
Labels: code, feature

#33 Fix/scene changer singleton
  Assets/Prefabs/UIPrefabs/README.md
  Assets/Prefabs/Utilities/Scene Changer.prefab
  Assets/Scenes/Credits.unity
  Assets/Scenes/Tests/DummyScene0.unity
  Assets/Scenes/Tests/DummyScene0.unity.meta
  Assets/Scenes/Tests/DummyScene1.unity
  Assets/Scenes/Tests/DummyScene1.unity.meta
  Assets/Scenes/Tests/testLevel.unity
  Assets/Scenes/Title.unity
  Assets/Scripts/SceneManagement/README.md
  Assets/Scripts/SceneManagement/SceneChanger.cs
  Assets/Scripts/SceneManagement/SceneManifest.cs
  Assets/Scripts/SceneManagement/SceneTransitionButton.cs
  Assets/Scripts/Tests/PlayMode/TestSceneChanger.cs
  Assets/Scripts/Tests/PlayMode/TestSceneTransitionButton.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: code, fix

#35 Added play sprite, enemy sprite, turret sprite, moon sprite, and back…
  Assets/Art/Sprites/AnimatedSprites/EnemyMissile_02.png
  Assets/Art/Sprites/AnimatedSprites/EnemyMissile_02.png.meta
  Assets/Art/Sprites/AnimatedSprites/Moon_Scaled 1.png
  Assets/Art/Sprites/AnimatedSprites/Moon_Scaled 1.png.meta
  Assets/Art/Sprites/AnimatedSprites/Moon_Scaled.png
  Assets/Art/Sprites/AnimatedSprites/Moon_Scaled.png.meta
  Assets/Art/Sprites/AnimatedSprites/PlayerMissile_02.png
  Assets/Art/Sprites/AnimatedSprites/PlayerMissile_02.png.meta
  Assets/Art/Sprites/AnimatedSprites/README.md
  Assets/Art/Sprites/AnimatedSprites/Turret_02.png
  Assets/Art/Sprites/AnimatedSprites/Turret_02.png.meta
  Assets/Art/Sprites/Environment/Space_Background_Final.png
  Assets/Art/Sprites/Environment/Space_Background_Final.png.meta
  Assets/Prefabs/Environment/Space_Background_Final.prefab
  Assets/Prefabs/Environment/Space_Background_Final.prefab.meta
  Assets/Scenes/Tests/ArtTest.unity
  Assets/Scenes/Tests/ArtTest.unity.meta
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset.meta
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF.asset.meta
  Assets/TextMesh Pro/Resources/Sprite Assets/EmojiOne.asset.meta
  Assets/TextMesh Pro/Resources/Style Sheets/Default Style Sheet.asset.meta
  Assets/TextMesh Pro/Resources/TMP Settings.asset.meta
  ProjectSettings/TagManager.asset
Labels: art
